import { Buffer } from 'node:buffer'
import { createServer } from 'node:http'
import { URL } from 'node:url'
import { deflateSync } from 'node:zlib'

import { verifyFixtureSet } from './fixture-verifier.mjs'

// Performance artwork is generated on demand rather than being added to the
// verified fixture set.  The dimensions are intentionally bounded both by
// the URL contract and by a conservative estimate of encoder working memory:
// raw scanlines, the zlib output, and the final PNG are all live briefly.
export const PERFORMANCE_IMAGE_MAX_DIMENSION = 2048
export const PERFORMANCE_IMAGE_MAX_GENERATION_BYTES = 32 * 1024 * 1024
export const PERFORMANCE_IMAGE_MAX_CACHE_BYTES = 8 * 1024 * 1024

const PNG_SIGNATURE = Buffer.from('89504e470d0a1a0a', 'hex')
const PNG_BYTES_PER_PIXEL = 4
const PNG_FIXED_OVERHEAD = 1 * 1024 * 1024
const PERFORMANCE_IMAGE_PARAM_PATTERN = /^([1-9]\d{0,9})[xXyY]([1-9]\d{0,9})$/

// PNG uses CRC-32 for each chunk.  Keeping the small table in this module
// avoids a dependency and makes the generated bytes reproducible everywhere.
const CRC_TABLE = new Uint32Array(256)
for (let index = 0; index < CRC_TABLE.length; index += 1) {
  let value = index
  for (let bit = 0; bit < 8; bit += 1) {
    value = value & 1 ? 0xedb88320 ^ (value >>> 1) : value >>> 1
  }
  CRC_TABLE[index] = value >>> 0
}

function crc32(value) {
  let checksum = 0xffffffff
  for (const byte of value) {
    checksum = CRC_TABLE[(checksum ^ byte) & 0xff] ^ (checksum >>> 8)
  }
  return (checksum ^ 0xffffffff) >>> 0
}

function writePngChunk(target, offset, type, data) {
  target.writeUInt32BE(data.byteLength, offset)
  target.write(type, offset + 4, 4, 'ascii')
  data.copy(target, offset + 8)
  const checksumStart = offset + 4
  const checksumEnd = offset + 8 + data.byteLength
  target.writeUInt32BE(crc32(target.subarray(checksumStart, checksumEnd)), checksumEnd)
  return checksumEnd + 4
}

function imageGenerationBytes(width, height) {
  const scanlineBytes = width * PNG_BYTES_PER_PIXEL + 1
  const rawBytes = scanlineBytes * height
  // The raw scanlines, deflate output, and final PNG can coexist. Three
  // raw-sized buffers plus zlib's fixed workspace is a deliberately
  // conservative upper bound.
  return rawBytes * 3 + PNG_FIXED_OVERHEAD
}

/**
 * Parse the image-size query used by the performance fixture.
 *
 * NetEase uses `param=96y96`; `x` is accepted as a readable alias for local
 * tests and hand-authored URLs.  The returned key always uses `x`, so both
 * spellings share one deterministic generated image and one request metric.
 */
export function parsePerformanceImageParam(requestUrl) {
  let url
  try {
    url = new URL(requestUrl ?? '/', 'http://127.0.0.1')
  } catch {
    return null
  }
  const values = url.searchParams.getAll('param')
  if (values.length !== 1) return null
  const match = PERFORMANCE_IMAGE_PARAM_PATTERN.exec(values[0])
  if (!match) return null

  const width = Number(match[1])
  const height = Number(match[2])
  if (
    !Number.isSafeInteger(width) ||
    !Number.isSafeInteger(height) ||
    width < 1 ||
    height < 1 ||
    width > PERFORMANCE_IMAGE_MAX_DIMENSION ||
    height > PERFORMANCE_IMAGE_MAX_DIMENSION ||
    imageGenerationBytes(width, height) > PERFORMANCE_IMAGE_MAX_GENERATION_BYTES
  ) {
    return null
  }
  return { height, key: `${width}x${height}`, width }
}

function stableHash(value) {
  let hash = 0x811c9dc5
  for (let index = 0; index < value.length; index += 1) {
    hash ^= value.charCodeAt(index)
    hash = Math.imul(hash, 0x01000193)
  }
  return hash >>> 0
}

function compressedPerformanceImageData(width, height, pixel) {
  const scanlineBytes = width * PNG_BYTES_PER_PIXEL + 1
  const raw = Buffer.allocUnsafe(scanlineBytes * height)
  const scanline = Buffer.allocUnsafe(scanlineBytes)
  scanline[0] = 0
  for (let offset = 1; offset < scanline.length; offset += PNG_BYTES_PER_PIXEL) {
    pixel.copy(scanline, offset)
  }
  for (let row = 0; row < height; row += 1) {
    scanline.copy(raw, row * scanlineBytes)
  }
  return deflateSync(raw)
}

function performancePng(pathname, dimensions) {
  const { height, width } = dimensions
  const seed = stableHash(`${pathname}?param=${dimensions.key}`)
  const pixel = Buffer.from([seed & 0xff, (seed >>> 8) & 0xff, (seed >>> 16) & 0xff, 0xff])
  const compressed = compressedPerformanceImageData(width, height, pixel)
  const header = Buffer.alloc(13)
  header.writeUInt32BE(width, 0)
  header.writeUInt32BE(height, 4)
  header[8] = 8 // bit depth
  header[9] = 6 // RGBA
  // Compression, filter, and interlace methods remain zero.
  const png = Buffer.allocUnsafe(
    PNG_SIGNATURE.byteLength + 12 + header.byteLength + 12 + compressed.byteLength + 12,
  )
  PNG_SIGNATURE.copy(png)
  let offset = PNG_SIGNATURE.byteLength
  offset = writePngChunk(png, offset, 'IHDR', header)
  offset = writePngChunk(png, offset, 'IDAT', compressed)
  writePngChunk(png, offset, 'IEND', Buffer.alloc(0))
  return png
}

function createPerformanceImageCache() {
  const entries = new Map()
  let bytes = 0
  let hits = 0
  let misses = 0

  function get(key, factory) {
    const cached = entries.get(key)
    if (cached) {
      entries.delete(key)
      entries.set(key, cached)
      hits += 1
      return cached
    }

    misses += 1
    const image = factory()
    if (image.byteLength <= PERFORMANCE_IMAGE_MAX_CACHE_BYTES) {
      entries.set(key, image)
      bytes += image.byteLength
      while (bytes > PERFORMANCE_IMAGE_MAX_CACHE_BYTES) {
        const oldestKey = entries.keys().next().value
        if (oldestKey === undefined) break
        const oldest = entries.get(oldestKey)
        entries.delete(oldestKey)
        bytes -= oldest?.byteLength ?? 0
      }
    }
    return image
  }

  return {
    get,
    snapshot() {
      return {
        bytes,
        entries: entries.size,
        hits,
        misses,
      }
    },
  }
}

function requestedFilename(requestUrl) {
  const rawPath = (requestUrl ?? '/').split('?')[0]
  if (!rawPath.startsWith('/')) {
    return null
  }

  let decodedPath
  try {
    decodedPath = decodeURIComponent(rawPath)
  } catch {
    return null
  }
  const filename = decodedPath.slice(1)
  if (
    filename.length === 0 ||
    filename.includes('/') ||
    filename.includes('\\') ||
    filename.includes('\0') ||
    filename === '.' ||
    filename === '..'
  ) {
    return null
  }
  return filename
}

export function parseByteRange(rangeHeader, size) {
  if (typeof rangeHeader !== 'string' || rangeHeader.includes(',')) {
    return null
  }
  const match = /^bytes=(\d*)-(\d*)$/.exec(rangeHeader)
  if (!match || (match[1].length === 0 && match[2].length === 0)) {
    return null
  }

  const [, startText, endText] = match
  const toSafeInteger = (value) => {
    if (value.length === 0 || !/^\d+$/.test(value)) {
      return null
    }
    const parsed = Number(value)
    return Number.isSafeInteger(parsed) ? parsed : null
  }

  if (startText.length === 0) {
    const suffixLength = toSafeInteger(endText)
    if (suffixLength === null || suffixLength === 0) {
      return null
    }
    return {
      end: size - 1,
      start: Math.max(0, size - suffixLength),
    }
  }

  const start = toSafeInteger(startText)
  if (start === null || start >= size) {
    return null
  }
  if (endText.length === 0) {
    return { end: size - 1, start }
  }

  const requestedEnd = toSafeInteger(endText)
  if (requestedEnd === null || requestedEnd < start) {
    return null
  }
  return { end: Math.min(size - 1, requestedEnd), start }
}

function endNotFound(response) {
  response.writeHead(404, { 'Content-Length': '0' })
  response.end()
}

function endRangeNotSatisfiable(response, size) {
  response.writeHead(416, {
    'Accept-Ranges': 'bytes',
    'Content-Length': '0',
    'Content-Range': `bytes */${size}`,
  })
  response.end()
}

function serveFile(request, response, fixture) {
  const { recipe } = fixture
  const rangeHeader = request.headers.range
  const range =
    rangeHeader === undefined ? undefined : parseByteRange(rangeHeader, fixture.byteLength)
  if (rangeHeader !== undefined && range === null) {
    endRangeNotSatisfiable(response, fixture.byteLength)
    return
  }

  const start = range?.start ?? 0
  const end = range?.end ?? fixture.byteLength - 1
  const contentLength = end - start + 1
  const headers = {
    'Accept-Ranges': 'bytes',
    'Content-Length': String(contentLength),
    'Content-Type': recipe.mimeType,
  }
  if (range) {
    headers['Content-Range'] = `bytes ${start}-${end}/${fixture.byteLength}`
  }

  response.writeHead(range ? 206 : 200, headers)
  if (request.method === 'HEAD') {
    response.end()
    return
  }
  if (!fixture.fileHandle || typeof fixture.fileHandle.createReadStream !== 'function') {
    response.destroy(new Error('Verified fixture file handle is unavailable'))
    return
  }

  const stream = fixture.fileHandle.createReadStream({ autoClose: false, end, start })
  stream.on('error', () => {
    response.destroy()
  })
  stream.pipe(response)
}

function listen(server, host, port) {
  return new Promise((resolve, reject) => {
    const onError = (error) => {
      server.off('listening', onListening)
      reject(error)
    }
    const onListening = () => {
      server.off('error', onError)
      resolve()
    }
    server.once('error', onError)
    server.once('listening', onListening)
    server.listen({ host, port })
  })
}

function closeServer(server) {
  if (!server.listening) {
    return Promise.resolve()
  }
  return new Promise((resolve, reject) => {
    server.close((error) => (error ? reject(error) : resolve()))
  })
}

function createRequestMetrics({ performanceImageCache } = {}) {
  let active = 0
  let total = 0
  let completed = 0
  let failed = 0
  let rangeRequests = 0
  let bytesSent = 0
  const byFilename = new Map()
  const byCacheKey = new Map()

  function incrementRequest(map, key) {
    const previous = map.get(key) ?? { requests: 0, failures: 0, bytesSent: 0 }
    map.set(key, { ...previous, requests: previous.requests + 1 })
  }

  function recordCompletion(map, key, { failure, length }) {
    const previous = map.get(key)
    if (!previous) return
    map.set(key, {
      ...previous,
      failures: previous.failures + (failure ? 1 : 0),
      bytesSent: previous.bytesSent + length,
    })
  }

  function begin({ filename, cacheKey = filename, ranged }) {
    active += 1
    total += 1
    if (ranged) rangeRequests += 1
    incrementRequest(byFilename, filename)
    incrementRequest(byCacheKey, cacheKey)
    let finished = false
    let declaredBytes = 0
    const finish = (response, isFailure = false) => {
      if (finished) return
      finished = true
      active = Math.max(0, active - 1)
      const failure =
        isFailure ||
        (response.statusCode ?? 0) >= 400 ||
        (response.destroyed && !response.writableEnded)
      if (failure) failed += 1
      else completed += 1
      const length = declaredBytes || Number(response.getHeader?.('content-length') ?? 0)
      const sentBytes = Number.isSafeInteger(length) && length > 0 ? length : 0
      bytesSent += sentBytes
      recordCompletion(byFilename, filename, { failure, length: sentBytes })
      recordCompletion(byCacheKey, cacheKey, { failure, length: sentBytes })
    }
    finish.setExpectedBytes = (value) => {
      if (Number.isSafeInteger(value) && value > 0) declaredBytes = value
    }
    return finish
  }

  return {
    begin,
    snapshot() {
      return {
        activeRequests: active,
        totalRequests: total,
        completedRequests: completed,
        failedRequests: failed,
        rangeRequests,
        bytesSent,
        byFilename: Object.fromEntries(
          [...byFilename.entries()].map(([filename, value]) => [filename, { ...value }]),
        ),
        byCacheKey: Object.fromEntries(
          [...byCacheKey.entries()].map(([cacheKey, value]) => [cacheKey, { ...value }]),
        ),
        performanceImageCache: performanceImageCache?.snapshot() ?? null,
      }
    },
  }
}

function performanceImageCacheKey(pathname, dimensions) {
  return dimensions ? `${pathname}?param=${dimensions.key}` : `${pathname}?param=<invalid>`
}

function endInvalidPerformanceImage(response) {
  response.writeHead(400, {
    'Cache-Control': 'no-store',
    'Content-Length': '0',
  })
  response.end()
}

export async function createFixtureRangeServer({
  directory,
  host = '127.0.0.1',
  port = 0,
  recipeManifestPath,
} = {}) {
  if (host !== '127.0.0.1') {
    throw new Error('Fixture range server must bind only to 127.0.0.1')
  }
  if (!Number.isInteger(port) || port < 0 || port > 65535) {
    throw new Error('Fixture range server port must be an integer from 0 to 65535')
  }

  const verifiedFixtureSet = await verifyFixtureSet({
    directory,
    recipeManifestPath,
    retainFileHandles: true,
  })
  let server
  let closePromise
  const performanceImageCache = createPerformanceImageCache()
  const metrics = createRequestMetrics({ performanceImageCache })
  try {
    server = createServer((request, response) => {
      let requestUrl
      try {
        requestUrl = new URL(request.url ?? '/', `http://${host}`)
      } catch {
        requestUrl = null
      }
      const pathname = requestUrl?.pathname ?? ''
      const performanceImage = pathname.startsWith('/clarus-perf/')
      const dimensions = performanceImage ? parsePerformanceImageParam(request.url) : null
      const cacheKey = performanceImage
        ? performanceImageCacheKey(pathname, dimensions)
        : (requestedFilename(request.url) ?? '<invalid>')
      const filename = performanceImage ? cacheKey : (requestedFilename(request.url) ?? '<invalid>')
      const finishMetrics = metrics.begin({
        cacheKey,
        filename,
        ranged: typeof request.headers.range === 'string',
      })
      let observedFailure = false
      response.once('finish', () => finishMetrics(response, observedFailure))
      response.once('close', () => {
        if (!response.writableEnded) observedFailure = true
        finishMetrics(response, observedFailure)
      })
      if (request.method !== 'GET' && request.method !== 'HEAD') {
        response.writeHead(405, { Allow: 'GET, HEAD', 'Content-Length': '0' })
        response.end()
        return
      }

      if (performanceImage) {
        if (!dimensions) {
          endInvalidPerformanceImage(response)
          return
        }
        const image = performanceImageCache.get(cacheKey, () =>
          performancePng(pathname, dimensions),
        )
        finishMetrics.setExpectedBytes(image.byteLength)
        response.writeHead(200, {
          'Cache-Control': 'public, max-age=31536000, immutable',
          'Content-Length': String(image.byteLength),
          'Content-Type': 'image/png',
        })
        if (request.method === 'HEAD') response.end()
        else response.end(image)
        return
      }

      const requested = requestedFilename(request.url)
      const fixture = requested ? verifiedFixtureSet.filesByName.get(requested) : undefined
      if (!fixture) {
        endNotFound(response)
        return
      }
      const range =
        typeof request.headers.range === 'string'
          ? parseByteRange(request.headers.range, fixture.byteLength)
          : undefined
      if (range || request.headers.range === undefined) {
        finishMetrics.setExpectedBytes(range ? range.end - range.start + 1 : fixture.byteLength)
      }
      serveFile(request, response, fixture)
    })
    await listen(server, host, port)
    const address = server.address()
    if (!address || typeof address === 'string') {
      throw new Error('Fixture range server did not receive a TCP address')
    }

    const close = () => {
      if (!closePromise) {
        closePromise = closeServer(server).finally(() => verifiedFixtureSet.close())
      }
      return closePromise
    }
    return {
      baseUrl: `http://${host}:${address.port}`,
      close,
      server,
      metrics,
      verifiedFixtureSet,
    }
  } catch (error) {
    await closeServer(server ?? { listening: false }).catch(() => {})
    await verifiedFixtureSet.close().catch(() => {})
    throw error
  }
}
